### ISSUE TITLE
[Suggestion] Add CS Gas for riot control scenarios

### ISSUE THREAD

**Issue by Eogos** [JShock1121/JSHK-Contamination-Area-Mod#2]
Would be very helpful to have CS Gas for riot control scenarios to disperse people, especially if it works against AI. Arma 3 seems to have several mods for lethal chemical warfare but not any CS Gas stuff, at least no good ones that I've seen.

**Comment by JShock1121** [comment]
Thank you for your input. However, your request is a bit too specific for the scope of this mod. You could use the add/remove area functions to fire dynamically on a smoke grenade, simulating a gas like effect along with this mod’s damaging effects. I don’t know if ACE still has their CS gas grenade or not, check that out if you haven’t. Sorry that I can’t be of more service.
